// src/utils/formFields.js
const formFieldsConfig = {
  land: [
    { field: "area", label: "Area (sqft)", type: "number", required: true },
    { field: "pricePerSqft", label: "Price Per Sqft", type: "number", required: true },
    { field: "totalPrice", label: "Total Price", type: "number", required: true },
    { field: "location", label: "Location", type: "text", required: true },
    { field: "pinCode", label: "Pin Code", type: "text", required: true },
    { field: "city", label: "City", type: "text", required: true },
    { field: "state", label: "State", type: "text", required: true },
    { field: "country", label: "Country", type: "text", required: true },
    { field: "photos", label: "Photos", type: "file", max: 5 },
    { field: "videos", label: "Videos", type: "file", max: 2 },
  ],

  flats: [
    { field: "area", label: "Area (sqft)", type: "number", required: true },
    { field: "facing", label: "Facing", type: "text", required: false },
    { field: "bedrooms", label: "Bedrooms", type: "number", required: true },
    { field: "balcony", label: "Balcony", type: "checkbox", required: false },
    { field: "bathrooms", label: "Bathrooms", type: "number", required: true },
    { field: "lift", label: "Lift", type: "checkbox", required: false },
    { field: "parking", label: "Parking", type: "checkbox", required: false },
    { field: "fourWheelerParking", label: "4-Wheeler Parking", type: "checkbox", required: false },
    { field: "powerBackup", label: "Power Backup", type: "checkbox", required: false },
    { field: "pricePerSqft", label: "Price Per Sqft", type: "number", required: true },
    { field: "totalPrice", label: "Total Price", type: "number", required: true },
    { field: "location", label: "Location", type: "text", required: true },
    { field: "pinCode", label: "Pin Code", type: "text", required: true },
    { field: "city", label: "City", type: "text", required: true },
    { field: "state", label: "State", type: "text", required: true },
    { field: "country", label: "Country", type: "text", required: true },
    { field: "photos", label: "Photos", type: "file", max: 5 },
    { field: "videos", label: "Videos", type: "file", max: 2 },
  ],

  villas: [
    { field: "area", label: "Area (sqft)", type: "number", required: true },
    { field: "facing", label: "Facing", type: "text", required: false },
    { field: "bedrooms", label: "Bedrooms", type: "number", required: true },
    { field: "balcony", label: "Balcony", type: "checkbox", required: false },
    { field: "bathrooms", label: "Bathrooms", type: "number", required: true },
    { field: "lift", label: "Lift", type: "checkbox", required: false },
    { field: "parking", label: "Parking", type: "checkbox", required: false },
    { field: "fourWheelerParking", label: "4-Wheeler Parking", type: "checkbox", required: false },
    { field: "powerBackup", label: "Power Backup", type: "checkbox", required: false },
    { field: "pricePerSqft", label: "Price Per Sqft", type: "number", required: true },
    { field: "totalPrice", label: "Total Price", type: "number", required: true },
    { field: "location", label: "Location", type: "text", required: true },
    { field: "pinCode", label: "Pin Code", type: "text", required: true },
    { field: "city", label: "City", type: "text", required: true },
    { field: "state", label: "State", type: "text", required: true },
    { field: "country", label: "Country", type: "text", required: true },
    { field: "photos", label: "Photos", type: "file", max: 5 },
    { field: "videos", label: "Videos", type: "file", max: 2 },
  ],

  apartments: [
    { field: "area", label: "Area (sqft)", type: "number", required: true },
    { field: "facing", label: "Facing", type: "text", required: false },
    { field: "bedrooms", label: "Bedrooms", type: "number", required: true },
    { field: "balcony", label: "Balcony", type: "checkbox", required: false },
    { field: "bathrooms", label: "Bathrooms", type: "number", required: true },
    { field: "lift", label: "Lift", type: "checkbox", required: false },
    { field: "parking", label: "Parking", type: "checkbox", required: false },
    { field: "fourWheelerParking", label: "4-Wheeler Parking", type: "checkbox", required: false },
    { field: "powerBackup", label: "Power Backup", type: "checkbox", required: false },
    { field: "pricePerSqft", label: "Price Per Sqft", type: "number", required: true },
    { field: "totalPrice", label: "Total Price", type: "number", required: true },
    { field: "location", label: "Location", type: "text", required: true },
    { field: "pinCode", label: "Pin Code", type: "text", required: true },
    { field: "city", label: "City", type: "text", required: true },
    { field: "state", label: "State", type: "text", required: true },
    { field: "country", label: "Country", type: "text", required: true },
    { field: "photos", label: "Photos", type: "file", max: 5 },
    { field: "videos", label: "Videos", type: "file", max: 2 },
  ],
};

module.exports = formFieldsConfig;
